### ISSUE TITLE
Rotary embedding exclusive for each Attention layer?

### ISSUE THREAD

**Issue by inspirit** [lucidrains/nGPT-pytorch#3]
Hi Phil!
I was wondering if there is some special idea/trick behind assigning Rotary Embedding for each Attention layer individually? :)
Cant we just use one in Transformer class?

https://github.com/lucidrains/nGPT-pytorch/blob/f64fba100e02eadafb257fb435866bcd66e702d2/nGPT_pytorch/nTransformer.py#L185

**Comment by lucidrains** [comment]
@inspirit hey yea, i was just being lazy :smile:

want to try submitting a pull request?

**Comment by inspirit** [comment]
well it will take sometime for me since i'm travelling and just browsing github to kill time :)

**Comment by lucidrains** [comment]
sg, i'll address this once i see more signal from the crowd, or from personal experiments

**Comment by lucidrains** [comment]
@inspirit seems like it is working for some researchers, so i got it done this morning

thanks for opening this

**Comment by inspirit** [comment]
Yeah, I wanted to let you know as well, that it worked nicely for me, in VAE setting as well as latent denoising

**Comment by lucidrains** [comment]
@inspirit that's really cool, did you compare it to non-normalized?

**Comment by inspirit** [comment]
yes, i compared it to vanilla transformer as well as skip transformer models

**Comment by inspirit** [comment]
to be exact i used the version from normalized_vit (which is simpler and easier to tackle :)) I've also enabled tokens l2 norm before passing them to transformer blocks, and quickly hacked version of value residual that you pushed to x_transformers recently, it all improved the performance a bit

**Comment by lucidrains** [comment]
thanks for sharing this Eugene! and yes, i saw the value residual effect immediately as well
