### ISSUE TITLE
why the initial value of alpha_init  is 1/layer_num

### ISSUE THREAD

**Issue by ghgmail** [lucidrains/nGPT-pytorch#7]
https://github.com/lucidrains/nGPT-pytorch/blob/5e76aac45044e065afd792006a0751b0f470f852/nGPT_pytorch/nTransformer.py#L324

hi, I want to know why the initial value of alpha_init  is 1/layer_num， Thanks for your reply

**Comment by lucidrains** [comment]
![Screenshot from 2024-10-22 09-32-40](https://github.com/user-attachments/assets/234ca78f-c9d8-4549-bd9a-c14b37e69dc9)

i'm following point 3 in section 2.6

**Comment by ghgmail** [comment]
> ![Screenshot from 2024-10-22 09-32-40](https://private-user-images.githubusercontent.com/108653/378933244-234ca78f-c9d8-4549-bd9a-c14b37e69dc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MTUwOTEsIm5iZiI6MTcyOTYxNDc5MSwicGF0aCI6Ii8xMDg2NTMvMzc4OTMzMjQ0LTIzNGNhNzhmLWM5ZDgtNDU0OS1iZDlhLWMxNGIzN2U2OWRjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxNjMzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGFmMTIzYTliMDkxYWU5NDI5ZTNjMzhjZDYzOTY5N2ExYTk1YTkzMzIyZDQ5OTBkZjQ1ZDU4ZGU0NzJiMWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PKRsEpxT3Nn8zmmk2_J9olvV3RVG8XNi3-POTqbw-6E)
> 
> i'm following point 3 in section 2.6

thank you very much，and I will close this issue
